# 기계 학습 실기 평가

###### 다음의 문제를 풀되 radom_state 값은 2020, 테스트 데이터의 크기는 전체 데이터의 20%로 할 것

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

#####  1번
iris 데이터에 대해서 sepal_width에 대한 회귀식을 구하고, RMSE값을 구하시오  
(sepal_legth, petal_length, petal_width 및 variety(품종)에 대한 회귀식임)

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
data = iris.data
label = iris.target

In [4]:
print(label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [30]:
columns = ['sepal_length','sepal_width','petal_length','petal_width']
irisDF = pd.DataFrame(iris.data, columns=columns)
irisDF.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [32]:
y = irisDF['sepal_width'].values
y[:3]

array([3.5, 3. , 3.2])

In [33]:
del irisDF['sepal_width']  # sepal_width열 삭제

In [34]:
irisDF.head(2)

sepal_length  petal_length  petal_width
0           5.1           1.4          0.2
1           4.9           1.4          0.2

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(irisDF,y, test_size = 0.2, shuffle=True, stratify = label, random_state = 2020)

- stratify : 지정한 Data의 비율을 유지한다. 예를 들어, Label Set인 Y가 25%의 0과 75%의 1로 이루어진 Binary Set일 때, stratify=Y로 설정하면 나누어진 데이터셋들도 0과 1을 각각 25%, 75%로 유지한 채 분할된다.


In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [36]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
rmse = np.round(np.sqrt(mean_squared_error(y_test, y_pred)),2)
rmse

0.33

In [37]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.3781454337043757

In [38]:
##coef() 함수를 통하여 회귀계수를 따로 출력
lr.coef_

array([ 0.65110826, -0.56700858,  0.48574622])

In [39]:
lr.intercept_  #절편값

0.7804751178903717

###### sepal_width에 대한 회귀식 

- sl = 0.637 sl - 0.535 pl + 0.558 pw - 0.126 v + 0.783

##### 2번
폐암 데이터(ThoraricSurgery.csv, 맨 마지막 열이 1년 생존여부임)에 대하여 svm, 결정트리, 로지스틱 회귀를 이용하여 1년 생존여부에 대하여
예측을 해보고 각각의 경우에 대해서 정확도를 구하시오

In [40]:
data_set = np.loadtxt("data/ThoraricSurgery.csv", delimiter=",")
data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [41]:
X = data_set[:, :-1]
Y = data_set[:, -1]
X.shape, Y.shape

((470, 17), (470,))

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2020)

In [43]:
## svm
from sklearn.svm import SVC
svc = SVC()  #객체 생성  

In [44]:
svc.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [45]:
y_pred_svc = svc.predict(x_test)

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_svc)

0.851063829787234

In [48]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [49]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [52]:
y_pred_dtc = dtc.predict(x_test)

In [53]:
accuracy_score(y_test,y_pred_dtc)

0.723404255319149

In [54]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()

In [55]:
lr_clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [57]:
y_pred_lr = lr_clf.predict(x_test)

In [58]:
accuracy_score(y_test, y_pred_lr)

0.8404255319148937

##### 3번
iris 데이터에 대해서 2차원으로 차원 축소한 뒤, k=2,3,4에 대해서 군집화를
해보고 성능을 평가하시오

In [ ]:
## 차원축소하렬면 공분산 먼저 구하고 ..

In [59]:
## 여러 속성을 PCA로 압축 하기 전에 각 속성값을 동일한 스케일로 변환 필요
from sklearn.preprocessing import StandardScaler

iris_std = StandardScaler().fit_transform(iris.data)

In [60]:
iris_std[:3, :]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ]])

In [62]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
pca_transformed = pca.fit_transform(iris_std)

In [65]:
columns = {'PCA1', 'PCA2'}
iris_pca_df = pd.DataFrame(data=pca_transformed, columns=columns)
iris_pca_df.head(3)

PCA1      PCA2
0 -2.264703  0.480027
1 -2.080961 -0.674134
2 -2.364229 -0.341908

In [86]:
iris_pca_df.values

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [66]:
from sklearn.cluster import KMeans

In [78]:
kmeans2 = KMeans(n_clusters=2, init='k-means++', max_iter=300,random_state=2020)  ##객체생성
kmeans2.fit(iris_pca_df)   ## 학습
k2result = kmeans2.labels_
k2result

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
kmeans3 = KMeans(n_clusters=3, init='k-means++', max_iter=300,random_state=2020)  ##객체생성
kmeans3.fit(pca_transformed)   ## 학습
k3result = kmeans3.labels_
k3result

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [80]:
kmeans4 = KMeans(n_clusters=4, init='k-means++', max_iter=300,random_state=2020)  ##객체생성
kmeans4.fit(pca_transformed)   ## 학습
k4result = kmeans4.labels_
k4result

array([3, 0, 0, 0, 3, 3, 0, 3, 0, 0, 3, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 0, 0, 3, 3, 0, 3, 3, 0, 0, 3,
       3, 0, 3, 0, 3, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2])

###### 실루엣계수
지금까지는 각각의 데이터가 원래 어떤 군집에 속해있었는지 정답(groundtruth)를 알고 있는 경우를 다루었다. 
하지만 이러한 정답 정보가 없다면 어떻게 군집화이 잘되었는지 판단할 수 있을까?
실루엣계수(Silhouette coefficient)는 이러한 경우에 군집화의 성능을 판단하기
위한 기준의 하나이다.

In [71]:
from sklearn.metrics import silhouette_samples, silhouette_score

In [81]:
average_score2 = silhouette_score(iris_pca_df.values, k2result)
average_score2  # 실루엣계수
## silhouette_score : 모든 데이터의 평균 실루엣 계수 값을 구함

0.614520203623045

In [82]:
average_score3 = silhouette_score(iris_pca_df.values, k3result)
average_score3

0.5091683341538228

In [83]:
average_score4 = silhouette_score(iris_pca_df.values, k4result)
average_score4

0.44450802349850316