# 기계 학습 실기 평가

###### 다음의 문제를 풀되 radom_state 값은 2020, 테스트 데이터의 크기는 전체 데이터의 20%로 할 것

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore') 

#####  1번
iris 데이터에 대해서 sepal_width에 대한 회귀식을 구하고, RMSE값을 구하시오  
(sepal_legth, petal_length, petal_width 및 variety(품종)에 대한 회귀식임)

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
data = iris.data
label = iris.target

In [4]:
print(label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [30]:
columns = ['sepal_length','sepal_width','petal_length','petal_width']
irisDF = pd.DataFrame(iris.data, columns=columns)
irisDF.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [32]:
y = irisDF['sepal_width'].values
y[:3]

array([3.5, 3. , 3.2])

In [33]:
del irisDF['sepal_width']  # sepal_width열 삭제

In [34]:
irisDF.head(2)

sepal_length  petal_length  petal_width
0           5.1           1.4          0.2
1           4.9           1.4          0.2

In [24]:
from sklearn.model_selection import train_test_split

In [35]:
x_train, x_test, y_train, y_test = \
    train_test_split(irisDF,y, test_size = 0.2, shuffle=True, stratify = label, random_state = 2020)

- stratify : 지정한 Data의 비율을 유지한다. 예를 들어, Label Set인 Y가 25%의 0과 75%의 1로 이루어진 Binary Set일 때, stratify=Y로 설정하면 나누어진 데이터셋들도 0과 1을 각각 25%, 75%로 유지한 채 분할된다.


In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [36]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
rmse = np.round(np.sqrt(mean_squared_error(y_test, y_pred)),2)
rmse

0.33

In [37]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.3781454337043757

In [38]:
##coef() 함수를 통하여 회귀계수를 따로 출력
lr.coef_

array([ 0.65110826, -0.56700858,  0.48574622])

In [39]:
lr.intercept_  #절편값

0.7804751178903717

###### sepal_width에 대한 회귀식 

- sl = 0.637 sl - 0.535 pl + 0.558 pw - 0.126 v + 0.783

##### 2번
폐암 데이터(ThoraricSurgery.csv, 맨 마지막 열이 1년 생존여부임)에 대하여 svm, 결정트리, 로지스틱 회귀를 이용하여 1년 생존여부에 대하여
예측을 해보고 각각의 경우에 대해서 정확도를 구하시오

In [40]:
data_set = np.loadtxt("data/ThoraricSurgery.csv", delimiter=",")
data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [41]:
X = data_set[:, :-1]
Y = data_set[:, -1]
X.shape, Y.shape

((470, 17), (470,))

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2020)

In [43]:
## svm
from sklearn.svm import SVC
svc = SVC()  #객체 생성  

In [44]:
svc.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [45]:
y_pred_svc = svc.predict(x_test)

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_svc)

0.851063829787234

In [48]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [49]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [52]:
y_pred_dtc = dtc.predict(x_test)

In [53]:
accuracy_score(y_test,y_pred_dtc)

0.723404255319149

In [54]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()

In [55]:
lr_clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [57]:
y_pred_lr = lr_clf.predict(x_test)

In [58]:
accuracy_score(y_test, y_pred_lr)

0.8404255319148937

##### 3번
iris 데이터에 대해서 2차원으로 차원 축소한 뒤, k=2,3,4에 대해서 군집화를
해보고 성능을 평가하시오

In [ ]:
## 차원축소하렬면 공분산 먼저 구하고 ..

In [59]:
## 여러 속성을 PCA로 압축 하기 전에 각 속성값을 동일한 스케일로 변환 필요
from sklearn.preprocessing import StandardScaler

iris_std = StandardScaler().fit_transform(iris.data)

In [60]:
iris_std[:3, :]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ]])

In [62]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
pca_transformed = pca.fit_transform(iris_std)

In [65]:
columns = {'PCA1', 'PCA2'}
iris_pca_df = pd.DataFrame(data=pca_transformed, columns=columns)
iris_pca_df.head(3)

PCA1      PCA2
0 -2.264703  0.480027
1 -2.080961 -0.674134
2 -2.364229 -0.341908

In [86]:
iris_pca_df.values

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [66]:
from sklearn.cluster import KMeans

In [78]:
kmeans2 = KMeans(n_clusters=2, init='k-means++', max_iter=300,random_state=2020)  ##객체생성
kmeans2.fit(iris_pca_df)   ## 학습
k2result = kmeans2.labels_
k2result

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
kmeans3 = KMeans(n_clusters=3, init='k-means++', max_iter=300,random_state=2020)  ##객체생성
kmeans3.fit(pca_transformed)   ## 학습
k3result = kmeans3.labels_
k3result

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [80]:
kmeans4 = KMeans(n_clusters=4, init='k-means++', max_iter=300,random_state=2020)  ##객체생성
kmeans4.fit(pca_transformed)   ## 학습
k4result = kmeans4.labels_
k4result

array([3, 0, 0, 0, 3, 3, 0, 3, 0, 0, 3, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3, 0, 0, 3, 3, 0, 3, 3, 0, 0, 3,
       3, 0, 3, 0, 3, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2])

###### 실루엣계수
지금까지는 각각의 데이터가 원래 어떤 군집에 속해있었는지 정답(groundtruth)를 알고 있는 경우를 다루었다. 
하지만 이러한 정답 정보가 없다면 어떻게 군집화이 잘되었는지 판단할 수 있을까?
실루엣계수(Silhouette coefficient)는 이러한 경우에 군집화의 성능을 판단하기
위한 기준의 하나이다.

In [71]:
from sklearn.metrics import silhouette_samples, silhouette_score

In [81]:
average_score2 = silhouette_score(iris_pca_df.values, k2result)
average_score2  # 실루엣계수
## silhouette_score : 모든 데이터의 평균 실루엣 계수 값을 구함

0.614520203623045

In [82]:
average_score3 = silhouette_score(iris_pca_df.values, k3result)
average_score3

0.5091683341538228

In [83]:
average_score4 = silhouette_score(iris_pca_df.values, k4result)
average_score4

0.44450802349850316

###### 4번
미드웨이 영화에 대한 네이버 리뷰(midway.tsv)에서 평점이 10점인 것은 긍정으로 7이하인
것은 부정으로 가정하고 감성 분석을 해 보시오

In [8]:
data = pd.read_csv('./data/midway.tsv', sep = "\t" , engine='python', encoding = "utf-8")
data.head(3)

Unnamed: 0  평점                일시                           감상평
0           0   9  2019.12.31 09:48    미드웨이가 재밌으면 추천 백두산이 재밌으면 비추
1           1  10  2019.12.31 10:41     저 해전이 있었기에 우리나라 광복도 가능 했음
2           2  10  2019.12.31 09:38  백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라

In [9]:
data.drop(data.columns[[0, 2]], axis=1, inplace=True)  ## 0,2열 삭제
data.head(3)

평점                           감상평
0   9    미드웨이가 재밌으면 추천 백두산이 재밌으면 비추
1  10     저 해전이 있었기에 우리나라 광복도 가능 했음
2  10  백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라

In [10]:
data['평점'].value_counts()

10    3071
8      513
9      468
6      216
7      169
1      107
4       97
2       90
5       68
3       26
Name: 평점, dtype: int64

In [11]:
positive = data['평점'] == 10
positive

0       False
1        True
2        True
3        True
4        True
        ...  
4820    False
4821    False
4822    False
4823    False
4824    False
Name: 평점, Length: 4825, dtype: bool

In [12]:
negative = data['평점'] <= 7
negative

0       False
1       False
2       False
3       False
4       False
        ...  
4820     True
4821     True
4822     True
4823     True
4824     True
Name: 평점, Length: 4825, dtype: bool

In [13]:
midway_pos = data[positive]
midway_pos

평점                                                감상평
1     10                          저 해전이 있었기에 우리나라 광복도 가능 했음
2     10                       백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라
3     10      방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.
4     10  교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...
5     10                      스케일 겁나커서 보는내내 입벌리고 봣네욬ㅋㅋ재밋습니다
...   ..                                                ...
4555  10  일본이 2차 세계 대전 때 항공모함 전투기 뇌격기 어뢰 만들어 , 미국과 맞짱을 뜰...
4576  10  크 같은 동아시아인으로써 일본 존경한다그래도 우리 조상분등도 저 전쟁을 함께 준비했...
4643  10                                   역시 대제국 일본 멋지다 만세
4662  10  백두산보단 못하다.하지만 서두 현실감있는 전쟁씬과 초반부터 화려하게 터지는 전쟁액션...
4700  10  진짜재밋게보고옴 이거보면 미국새끼들이 OO이고 잘못을 먼저해서 일본이 공격한 역사를...

[3071 rows x 2 columns]

In [14]:
midway_pos['class'] = np.ones(len(midway_pos),int)  ## 1로 초기화된 배열을 생성
midway_pos.head(3)

평점                                            감상평  class
1  10                      저 해전이 있었기에 우리나라 광복도 가능 했음      1
2  10                   백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라      1
3  10  방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.      1

In [16]:
midway_neg = data[negative]
midway_neg['class'] = np.zeros(len(midway_neg), int)

In [19]:
midway_df = pd.concat([midway_pos, midway_neg])  ##dataFrame 합치기
midway_df

평점                                                감상평  class
1     10                          저 해전이 있었기에 우리나라 광복도 가능 했음      1
2     10                       백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라      1
3     10      방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.      1
4     10  교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...      1
5     10                      스케일 겁나커서 보는내내 입벌리고 봣네욬ㅋㅋ재밋습니다      1
...   ..                                                ...    ...
4820   1  대만에서 10월31일 개봉했었는데.성공못했음. 미국에서도 성적이 별로구..그이유가 ...      0
4821   2  아니 이게 재밌다는 사람은 뭐야?;그냥 국뽕->미국뽕 이 차이밖에 없는데 이 영화가...      0
4822   2                  시간이 아까워요. 엉성한 그래서 감동도 교훈도 없는...ㅉㅉ      0
4823   4                   진주만보다 낫다고해서봤는데대실망...천조국,왜놈들 국뽕영화      0
4824   1  우리는 왜 이런 영화 못만드냐? 싸구려 좌파 찌라시 백x산이나 대놓고 친북사상 반일...      0

[3844 rows x 3 columns]

In [20]:
del midway_df['평점']
midway_df.head()

감상평  class
1                          저 해전이 있었기에 우리나라 광복도 가능 했음      1
2                       백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라      1
3      방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.      1
4  교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...      1
5                      스케일 겁나커서 보는내내 입벌리고 봣네욬ㅋㅋ재밋습니다      1

In [21]:
midway_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3844 entries, 1 to 4824
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   감상평     3397 non-null   object
 1   class   3844 non-null   int32 
dtypes: int32(1), object(1)
memory usage: 75.1+ KB


In [22]:
midway_df.dropna(inplace = True)
midway_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3397 entries, 1 to 4824
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   감상평     3397 non-null   object
 1   class   3397 non-null   int32 
dtypes: int32(1), object(1)
memory usage: 66.3+ KB


In [25]:
X_train, X_test, y_train, y_test = \
    train_test_split(midway_df['감상평'], midway_df['class'], test_size=0.2, 
                     stratify=midway_df['class'], random_state=2020)
X_train.shape, X_test.shape

((2717,), (680,))

In [26]:
from konlpy.tag import Okt

okt = Okt()

def okt_tokenizer(text):
    # 입력 인자로 들어온 text를 형태소 단어로 토큰화하여 list 객체 반환
    tokens_ko = okt.morphs(text)
    return tokens_ko

ModuleNotFoundError: No module named 'konlpy'