# 기계 학습 실기 평가

##### 다음의 문제를 풀되 radom_state 값은 2020, 테스트 데이터의 크기는 전체 데이터의 20%로 할 것

In [3]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
## 1번w

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()

In [149]:
data = iris.data
label = iris.target

In [150]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(data,label, test_size = 0.2, shuffle=True, stratify = label, random_state = 2020)

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [14]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
rmse = np.round(np.sqrt(mean_squared_error(y_test, y_pred)),2)
rmse

0.2

In [ ]:
# 2번

In [36]:
thoraricSur_df = pd.read_csv('./data/ThoraricSurgery.csv', header=None)
thoraricSur_df.head()

0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0  293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   0
1    1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   0
2    8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   1
3   14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   1
4   17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   0

In [32]:
x_data = thoraricSur_df.iloc[:, 0:17]   #1열 ~ 17열 - 한자상태
y_data = thoraricSur_df.iloc[:, 17]     #18열 - 생존여부

In [33]:
## svm
from sklearn.svm import SVC
svc = SVC()  #객체 생성  

In [34]:
svc

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [161]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [162]:
dtc

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [163]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()

In [37]:
### 3번   차원축소하렬면 공분산 먼저 구하고 ..

In [38]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
pca_transformed = pca.fit_transform(iris.data)

In [40]:
from sklearn.cluster import KMeans

In [42]:
kmeans2 = KMeans(n_clusters=2, init='k-means++', max_iter=300,random_state=0)  ##객체생성
kmeans2.fit(pca_transformed)   ## 학습
kmeans2.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
kmeans3 = KMeans(n_clusters=3, init='k-means++', max_iter=300,random_state=0)  ##객체생성
kmeans3.fit(pca_transformed)   ## 학습
kmeans3.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [45]:
kmeans4 = KMeans(n_clusters=4, init='k-means++', max_iter=300,random_state=0)  ##객체생성
kmeans4.fit(pca_transformed)   ## 학습
kmeans4.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 3, 1, 3, 1, 3, 1, 3, 3, 3, 3, 1, 3, 1,
       3, 3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 1, 3, 1, 1, 1,
       3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 3, 3, 2, 1, 2, 1, 2, 2, 3, 2, 2, 2,
       1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1])

In [160]:
kmeans2.fit(x_train, y_train)
y_pred2 = kmeans2.predict(x_test)

In [152]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.0

In [153]:
kmeans3.fit(x_train, y_train)
y_pred3 = kmeans3.predict(x_test)

In [154]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred3)

0.23333333333333334

In [155]:
kmeans4.fit(x_train, y_train)
y_pred4 = kmeans4.predict(x_test)

In [156]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred4)

0.23333333333333334

In [60]:
# 4번

In [82]:
import csv
f = open('midway.tsv', 'w', encoding='utf-8', newline='')
wr = csv.writer(f, delimiter='\t')

In [122]:
dataset = pd.read_csv("./data/midway.tsv", delimiter='\t', header=0)

print(dataset)

      Unnamed: 0  평점                일시  \
0              0   9  2019.12.31 09:48   
1              1  10  2019.12.31 10:41   
2              2  10  2019.12.31 09:38   
3              3  10  2019.12.31 09:14   
4              4  10  2019.12.31 19:58   
...          ...  ..               ...   
4820        4820   1  2019.12.31 09:11   
4821        4821   2  2020.01.05 20:41   
4822        4822   2  2020.01.01 23:40   
4823        4823   4  2019.12.31 15:37   
4824        4824   1  2020.01.16 23:51   

                                                    감상평  
0                            미드웨이가 재밌으면 추천 백두산이 재밌으면 비추  
1                             저 해전이 있었기에 우리나라 광복도 가능 했음  
2                          백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라  
3         방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.  
4     교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...  
...                                                 ...  
4820  대만에서 10월31일 개봉했었는데.성공못했음. 미국에서도 성적이 별로구..그이유가 ...  
4821  아니 이게 재밌다는 사람은 뭐야?;그냥 국뽕-

In [121]:
data = pd.read_csv('./data/midway.tsv', sep = "\t" , engine='python', encoding = "utf-8")
data.head()

Unnamed: 0  평점                일시  \
0           0   9  2019.12.31 09:48   
1           1  10  2019.12.31 10:41   
2           2  10  2019.12.31 09:38   
3           3  10  2019.12.31 09:14   
4           4  10  2019.12.31 19:58   

                                                 감상평  
0                         미드웨이가 재밌으면 추천 백두산이 재밌으면 비추  
1                          저 해전이 있었기에 우리나라 광복도 가능 했음  
2                       백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라  
3      방금 개봉했는데 1점 준애는 뭐냐 ㅋㅋ 일본놈이냐? 이제 광고돌고 있을 시간이다.  
4  교과서에는 미드웨이 해전에서 미국이 승리했다고 한 줄로 서술되어 있지만 단순히 한 ...

In [140]:
star_score = []
for i in data:
    star_score.append(data[i][0])
